# id: 1
server:
  address: "server:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 10
bet:
  name: "Santiago Lionel"
  surname: "Lorca"
  id: 12345678
  birthdate: "1990-03-17"
  number: 7574
